import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Phone, Mail, Globe, MapPin, Clock, Bus, Utensils, Bed, Download } from "lucide-react";
import { jsPDF } from "jspdf";
import { schools } from "@/data/schools";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { MapEmbed } from "@/components/MapEmbed";

const requiredDocs = [
  "Child's Birth Certificate",
  "Parent/Guardian ID",
  "Proof of Address",
  "Autism Assessment / Diagnosis",
  "Medical Report",
  "Immunization Record",
  "Previous School Report (if transferring)",
  "Clinic Card",
  "Passport Photo (if required)",
];

export const Route = createFileRoute("/schools/$id")({
  loader: ({ params }) => {
    const school = schools.find((s) => s.id === params.id);
    if (!school) throw notFound();
    return { school };
  },
  head: ({ loaderData }) => ({
    meta: loaderData
      ? [
          { title: `${loaderData.school.name} — Autism Connect EC` },
          { name: "description", content: loaderData.school.description },
          { property: "og:title", content: loaderData.school.name },
          { property: "og:description", content: loaderData.school.description },
        ]
      : [],
  }),
  notFoundComponent: () => (
    <div className="mx-auto max-w-2xl px-4 py-20 text-center">
      <h1 className="text-2xl font-bold">School not found</h1>
      <p className="mt-2 text-muted-foreground">We couldn't find this school.</p>
      <Button asChild className="mt-6"><Link to="/schools">Back to schools</Link></Button>
    </div>
  ),
  errorComponent: ({ error, reset }) => (
    <div className="mx-auto max-w-2xl px-4 py-20 text-center">
      <h1 className="text-2xl font-bold">Something went wrong</h1>
      <p className="mt-2 text-muted-foreground">{error.message}</p>
      <Button className="mt-6" onClick={reset}>Try again</Button>
    </div>
  ),
  component: SchoolDetailPage,
});

function downloadChecklist(schoolName: string) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text("Application Documents Checklist", 20, 20);
  doc.setFontSize(12);
  doc.text(schoolName, 20, 30);
  doc.setFontSize(11);
  let y = 45;
  requiredDocs.forEach((d, i) => {
    doc.rect(20, y - 4, 5, 5);
    doc.text(`${i + 1}. ${d}`, 30, y);
    y += 10;
  });
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by Autism Connect Eastern Cape", 20, 280);
  doc.save(`${schoolName.replace(/\s+/g, "-")}-checklist.pdf`);
}

function SchoolDetailPage() {
  const { school } = Route.useLoaderData();

  return (
    <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
      <Link to="/schools" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">
        <ArrowLeft className="h-4 w-4" aria-hidden /> Back to schools
      </Link>

      <header className="mt-4 grid gap-4 sm:flex sm:items-start sm:justify-between">
        <div className="min-w-0">
          <h1 className="text-3xl font-bold sm:text-4xl">{school.name}</h1>
          <p className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-muted-foreground">
            <span className="inline-flex items-center gap-1"><MapPin className="h-4 w-4" aria-hidden /> {school.address}</span>
          </p>
          <div className="mt-3 flex flex-wrap gap-2">
            <Badge variant="secondary">Ages {school.ageMin}–{school.ageMax}</Badge>
            <Badge variant="secondary">{school.gender}</Badge>
            <Badge variant="secondary">{school.district}</Badge>
            {school.admissionOpen ? (
              <Badge className="bg-success text-success-foreground hover:bg-success">Admissions open</Badge>
            ) : (
              <Badge variant="outline">Waiting list</Badge>
            )}
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button asChild><a href={`tel:${school.phone.replace(/\s/g, "")}`}><Phone className="mr-2 h-4 w-4" />Call</a></Button>
          <Button asChild variant="outline"><a href={`mailto:${school.email}`}><Mail className="mr-2 h-4 w-4" />Email</a></Button>
        </div>
      </header>

      <div className="mt-8 grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <Card>
            <CardHeader><CardTitle>About the school</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground">{school.description}</p>
              <dl className="grid gap-x-6 gap-y-3 text-sm sm:grid-cols-2">
                {school.principal && <Row label="Principal" value={school.principal} />}
                <Row label="Phone" value={school.phone} />
                <Row label="Email" value={school.email} />
                {school.website && <Row label="Website" value={school.website} link />}
                <Row label="Operating hours" value={school.operatingHours} icon={<Clock className="h-4 w-4" />} />
                <Row label="Transport" value={school.transportation ? "Available" : "Not provided"} icon={<Bus className="h-4 w-4" />} />
                <Row label="Meals" value={school.meals ? "Provided" : "Not provided"} icon={<Utensils className="h-4 w-4" />} />
                <Row label="Boarding" value={school.boarding ? "Available" : "Day school only"} icon={<Bed className="h-4 w-4" />} />
              </dl>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Therapy services</p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {school.therapyServices.map((t) => <Badge key={t} variant="secondary">{t}</Badge>)}
                </div>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Activities offered</p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {school.activities.map((a) => <Badge key={a} variant="outline">{a}</Badge>)}
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex flex-wrap items-center justify-between gap-3">
                <CardTitle>Required application documents</CardTitle>
                <Button size="sm" variant="outline" onClick={() => downloadChecklist(school.name)}>
                  <Download className="mr-2 h-4 w-4" /> Download checklist (PDF)
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <ul className="grid gap-3 sm:grid-cols-2">
                {requiredDocs.map((d, i) => (
                  <li key={d} className="flex items-start gap-3 rounded-lg border p-3">
                    <Checkbox id={`doc-${i}`} aria-label={d} />
                    <label htmlFor={`doc-${i}`} className="text-sm leading-tight">{d}</label>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle>Location</CardTitle></CardHeader>
            <CardContent>
              <MapEmbed query={school.mapsQuery} title={`Map of ${school.name}`} />
              <Button asChild variant="outline" className="mt-3">
                <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${encodeURIComponent(school.mapsQuery)}`}>
                  Open in Google Maps
                </a>
              </Button>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader><CardTitle>Admission information</CardTitle></CardHeader>
            <CardContent className="space-y-3 text-sm">
              <Row label="Age accepted" value={`${school.ageMin} – ${school.ageMax} years`} />
              <Row label="Gender" value={school.gender} />
              <Row label="Diagnosis required" value="Autism assessment required" />
              <Row label="Fees" value={school.fees} />
              <Row label="Government funding" value={school.governmentFunding} />
              <Row label="Application opens" value={school.applicationOpens} />
              <Row label="Waiting list" value={school.waitingList} />
              <Button className="mt-3 w-full" disabled={!school.admissionOpen}>
                {school.admissionOpen ? "Apply now" : "Join waiting list"}
              </Button>
              <p className="text-xs text-muted-foreground">Application submitted through the school directly.</p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

function Row({ label, value, link, icon }: { label: string; value: string; link?: boolean; icon?: React.ReactNode }) {
  return (
    <div>
      <dt className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        {icon}{label}
      </dt>
      <dd className="mt-0.5 text-sm">
        {link ? <a className="text-primary hover:underline" href={value} target="_blank" rel="noreferrer">{value}</a> : value}
      </dd>
    </div>
  );
}
